//
// Format:
//
// DebugPoint "x y z level mode note_text..."
//
// e.g.
// DebugPoint "0.0 0 0.0 FA_T111 All This is the origin"
// DebugPoint "10 -20 30.5 FA_T721 A There is a horrible seam here"

//These are the custom points. 



// Quick nav 121 start to finish
DebugPointCamPos "-504.22 -423.14 31.24"
DebugPoint "-504.50 -412.92 29.37 T121 All Quick Nav (01)"

DebugPointCamPos "-502.21 11.00 33.33"
DebugPoint "-483.46 -20.29 20.02 T121 All Quick Nav (02)"

DebugPointCamPos "-319.06 207.51 27.82"
DebugPoint "-314.70 203.88 25.40 T121 All Quick Nav (03)"

DebugPointCamPos "19.90 123.82 17.21"
DebugPoint "83.64 84.28 0.29 T121 All Quick Nav (04)"

DebugPointCamPos "395.36 -224.21 3.17"
DebugPoint "389.58 -257.07 -8.58 T121 All Quick Nav (05)"

DebugPointCamPos "579.27 -509.51 5.30"
DebugPoint "563.47 -487.80 -9.79 T121 All Quick Nav (06)"

DebugPointCamPos "670.39 116.06 8.09"
DebugPoint "670.15 154.98 -7.83 T121 All Quick Nav (07)"

DebugPointCamPos "654.17 750.60 2.98"
DebugPoint "644.71 747.67 0.45 T121 All Quick Nav (08)"

DebugPointCamPos "333.59 1077.39 14.94"
DebugPoint "344.91 1072.40 12.76 T121 All Quick Nav (09)"

DebugPointCamPos "891.42 954.74 -1.01"
DebugPoint "802.14 965.73 -12.14 T121 All Quick Nav (10)"



// Quick nav 121 start to finish
DebugPointCamPos "430.02 391.54 30.53"
DebugPoint "413.11 413.35 22.07 Mstr_Entertainment All Quick Nav (01)"

DebugPointCamPos "306.35 313.40 20.14"
DebugPoint "301.92 313.18 18.75 Mstr_Entertainment All Quick Nav (02)"

DebugPointCamPos "473.95 -162.60 18.38"
DebugPoint "473.86 -158.59 17.30 Mstr_Entertainment All Quick Nav (03)"

DebugPointCamPos "757.48 -1.06 35.90"
DebugPoint "759.14 -34.00 24.82 Mstr_Entertainment All Quick Nav (04)"

DebugPointCamPos "1087.03 -27.04 29.91"
DebugPoint "1068.93 -30.89 20.14 Mstr_Entertainment All Quick Nav (05)"

DebugPointCamPos "930.39 337.93 48.05"
DebugPoint "929.30 334.28 47.10 Mstr_Entertainment All Quick Nav (06)"

DebugPointCamPos "528.45 2.18 25.43"
DebugPoint "532.93 30.25 22.67 Mstr_Entertainment All Quick Nav (07)"

DebugPointCamPos "540.87 250.31 47.05"
DebugPoint "508.35 260.35 26.30 Mstr_Entertainment All Quick Nav (08)"



// Leave this line here.  It runs the report generated by Raid
run DebugPointsReport
