//
//  mod2k.psc - common configuration file for mod2k
//

strPil "dw_piLX2" // <-- Paul Glinker: added Monday April 17, 2006

// RestoreWinInfo   // use SaveWinInfo in mod2k


// Video
dxDrawSilo 0
dxDrawShadow 0

dxWinExtents 1

EnableSurfaceBreakup 1
background_color 0
kdop_draw_cull_dist 1024
vertexPaintCache 0

smartFileNameCache 1
lazyChunkUpdate 1

// Audio



draw_dots_per_second3d 32   // tessellation of paths
fpuVerbose 0
pitaDebug 1


pitchInvert 1
doIntroSequence 0

bind joy0_dpadright+joy0_l3 GotoDebugPoint +1
bind joy0_dpadleft+joy0_l3  GotoDebugPoint -1
bind joy0_dpaddown+joy0_l3  GotoDebugPointNearest    0   // l3+dpaddown
bind joy0_dpadup+joy0_l3    GotoDebugPointNearestCam 0   // l3+dpadup
bind joy0_x+joy0_r3 ToggleDebugCam 1
bind joy0_r1+joy0_r3 TeleportToTarget 0   // r3+black
bind joy0_square+joy0_dpadup nukeme 0
bind joy0_x+joy0_dpaddown toggleai 0

disable_reload 1 // if you don't want to reload

targetPlatform 3 // 3 = Win32



run game.psc             // generated by makebuild
pitaDebug 1
isdeveloperbuild 1       // Use developerbuild for mod
disablePitaNote 0

run texture_presets      // common file, copied from shared
run mod2kLocal.psc       // your own configuration options
run CareerScript.psc    // must be after local settings (or else makebuild breaks)

mountArchives 1		 // adds files contained in .pfa archives to file system
useArchives 1		 // allows file operations to access file archives

ultraFileNameCache 1	 // AWO: uses delta file caching system

