run CompetitorLoadouts
 
// NOTE: 05/22/06 Mount ID List:
//
// 0 front left/right (side is determined by sign of local c's y offset)
// 1 roof
// 2 rear center
// 3 front center
// 4 trunk
// 5 front bumper
 
// The car exploder is in rh_FX_Explosion. you can adjust damage and radius in mod.
 
// NOTE: [jh] 11/27/05
// the weaponIDs are still accurate, but I removed the unused weapons to
// speed up psc processing. They still exist in memory as I was afraid someone was
// reffing them by id# and did not want to change that.
 
//this is the master damage tuner handle for damage AI does to the player
// 0.3 means the AI does 1/3 the weapon damage.
g_playerDamageGain 1
 
// size of reticule on screen
g_reticuleScale .1
 
// relative reticule screen coordinates "x y" (".5 .5" is screen center, "0 0" is top left)
g_farChaseReticuleSc ".5 .57"
g_chaseReticuleSc ".5 .5"
g_bumperReticuleSc ".5 .48"
g_driverReticuleSc ".5 .43"
g_customReticuleSc ".5 .55"
 
//g_weaponsSafetyTime 5
g_weaponsSafetyTime 20
 
// re-centering reticle Kp/Kd scaling. 1.0 for no difference from move
g_returnReticleKpScale .35
g_returnReticleKdScale .35
 
// locked-on-target reticle Kp/Kd scaling. 1.0 for no difference from move
g_lockedReticleKpScale .25
g_lockedReticleKdScale .25
 
// aimMode 0 is dumbfire, 1 is firstorder deadreckoning autoaim cone, 2 is manual.
//-----------------------------------------------------------------------------
//   Weapon Tuning File
//-----------------------------------------------------------------------------
// last weapon FX message: 54
 
//-----------------------------------------------------------------------------
// weaponId 0
MorphingWeaponSetId "EmptyWeapon"
MorphingWeaponSetData "name = Empty Weapon"
MorphingWeaponSetData "meshId = -1"
MorphingWeaponSetData "fireMessages = 0"
MorphingWeaponSetData "projectilePid = NULL"
MorphingWeaponSetData "iconId = 0"
//-----------------------------------------------------------------------------
// weaponId 1
MorphingWeaponSetId "MachineGuns"
MorphingWeaponSetData "name = Machine Guns"
MorphingWeaponSetData "aimMode = 2"
MorphingWeaponSetData "aimConePitchAngle = 40"
MorphingWeaponSetData "aimConeYawAngle = 45"
MorphingWeaponSetData "firingRate = 25.0"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = .1"
MorphingWeaponSetData "spreadAngleY = .1"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 8"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 4"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = jh_Bullet"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 6"
MorphingWeaponSetData "projectileMinDamage = 6"
MorphingWeaponSetData "projectileSpeed = 200.0"
MorphingWeaponSetData "projectileSpeedOffset = 10.0"
MorphingWeaponSetData "projectileRange = 72.0"
MorphingWeaponSetData "projectileMass = .1"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 72.0"
MorphingWeaponSetData "exploderBlastForce = 0.0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.125"
MorphingWeaponSetData "fireRumbleLeftMotor = 0.35"
MorphingWeaponSetData "fireMessages = 5"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "shellCasingMessage = 23"
MorphingWeaponSetData "shellCasingTriggerLogic = 10"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 1"
MorphingWeaponSetData "mountId = 0"
MorphingWeaponSetData "meshId = 0"
MorphingWeaponSetData "alternateMeshId = 1"
MorphingWeaponSetData "reticule = 6"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 2
MorphingWeaponSetId "ScatterGun"
MorphingWeaponSetData "name = Shotgun"
MorphingWeaponSetData "aimMode=2"
MorphingWeaponSetData "aimConePitchAngle = 40"
MorphingWeaponSetData "aimConeYawAngle = 120"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = False"
MorphingWeaponSetData "spreadAngleX = 0.5"
MorphingWeaponSetData "spreadAngleY = 0.2"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 4"
MorphingWeaponSetData "reloadDelay = 3"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 2.0"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_ShotgunPellet"
MorphingWeaponSetData "projectileCount = 15"
MorphingWeaponSetData "projectileMaxDamage = 10"
MorphingWeaponSetData "projectileMinDamage = 10"
MorphingWeaponSetData "projectileSpeed = 128.0"
MorphingWeaponSetData "projectileSpeedOffset = 64.0"
MorphingWeaponSetData "projectileRange = 48"
MorphingWeaponSetData "projectileMass = 4"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 40.0"
MorphingWeaponSetData "exploderBlastForce = 0.0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 0.0"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 1.0"
MorphingWeaponSetData "fireMessages = 10"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.25"
MorphingWeaponSetData "rumbleLeftMotor = 1.0"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "shellCasingMessage = 23"
MorphingWeaponSetData "shellCasingTriggerLogic = 1"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 2"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 15"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 5"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 3
MorphingWeaponSetId "ReverseScatterGun"
MorphingWeaponSetData "name = Rear Shotgun"
MorphingWeaponSetData "aimMode = 0"
MorphingWeaponSetData "aimConePitchAngle = 0"
MorphingWeaponSetData "aimConeYawAngle = 0"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = False"
MorphingWeaponSetData "spreadAngleX = 3"
MorphingWeaponSetData "spreadAngleY = 1"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 5"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1.0"
MorphingWeaponSetData "fullReloadPenalty = 1.0"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_ShotgunPellet"
MorphingWeaponSetData "projectileCount = 20"
MorphingWeaponSetData "projectileMaxDamage = 10"
MorphingWeaponSetData "projectileMinDamage = 10"
MorphingWeaponSetData "projectileSpeed = 128.0"
MorphingWeaponSetData "projectileSpeedOffset = 64.0"
MorphingWeaponSetData "projectileRange = 36.0"
MorphingWeaponSetData "projectileMass = 3"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 2"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 36.0"
MorphingWeaponSetData "exploderBlastForce = 0.0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 0.0"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 1.0"
MorphingWeaponSetData "fireMessages = 2"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.25"
MorphingWeaponSetData "rumbleLeftMotor = 1.0"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "shellCasingMessage = 23"
MorphingWeaponSetData "shellCasingTriggerLogic = 1"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 2"
MorphingWeaponSetData "mountId = 2"
MorphingWeaponSetData "meshId = 3"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 0"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 4
MorphingWeaponSetId "ECMSmoker"
MorphingWeaponSetData "name = Smokescreen"
MorphingWeaponSetData "aimMode = 0"
MorphingWeaponSetData "aimConePitchAngle = 0"
MorphingWeaponSetData "aimConeYawAngle = 0"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 6"
MorphingWeaponSetData "reloadDelay = 5"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 3"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_SmokeScreen"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 0"
MorphingWeaponSetData "projectileMinDamage = 0"
MorphingWeaponSetData "projectileSpeed = 0.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 1024.0"
MorphingWeaponSetData "projectileMass = 0.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 0.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 3"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 1024.0"
MorphingWeaponSetData "exploderMinDamage = 0"
MorphingWeaponSetData "exploderMaxDamage = 0"
MorphingWeaponSetData "exploderBlastForce = 6.0"
MorphingWeaponSetData "exploderMinBlastRadius = 0.0"
MorphingWeaponSetData "exploderMedBlastRadius = 0.0"
MorphingWeaponSetData "exploderFullBlastRadius = 0.0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireMessages = 0"
MorphingWeaponSetData "offMessages = 41"
MorphingWeaponSetData "onMessages = 40"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "smokeLifeTime = 4.0"
MorphingWeaponSetData "smokeStunTime = 4.0"
MorphingWeaponSetData "ECM = 1"
MorphingWeaponSetData "iconId = 4"
MorphingWeaponSetData "mountId = 2"
MorphingWeaponSetData "meshId = 8"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 0"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 5
MorphingWeaponSetId "Grenadier"
MorphingWeaponSetData "name = Grenades"
MorphingWeaponSetData "aimMode = 2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 90"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = .12"
MorphingWeaponSetData "maxFireTime = 4"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 3"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = jh_Grenade"
MorphingWeaponSetData "projectileCount = 5"
MorphingWeaponSetData "projectileMaxDamage = 0"
MorphingWeaponSetData "projectileMinDamage = 0"
MorphingWeaponSetData "projectileSpeed = 40.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 64.0"
MorphingWeaponSetData "projectileMass = 1.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 64.0"
MorphingWeaponSetData "exploderMinDamage = 10"
MorphingWeaponSetData "exploderMaxDamage = 26"
MorphingWeaponSetData "exploderBlastForce = 200.0"
MorphingWeaponSetData "exploderMinBlastRadius = 4.0"
MorphingWeaponSetData "exploderMedBlastRadius = 3.0"
MorphingWeaponSetData "exploderFullBlastRadius = 2.0"
MorphingWeaponSetData "exploderDetonationDelay = 2.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = .5"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = .5"
MorphingWeaponSetData "exploderRumbleLeftMotor = .5"
MorphingWeaponSetData "exploderRumbleRightMotor = .5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 0.5"
MorphingWeaponSetData "fireRumbleDuration = 0.125"
MorphingWeaponSetData "fireRumbleLeftMotor = .5"
MorphingWeaponSetData "fireMessages = 29"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "smokeLifeTime = 4.0"
MorphingWeaponSetData "smokeStunTime = 4.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 5"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 10"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 7"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 6
MorphingWeaponSetId "ECMSprayer"
MorphingWeaponSetData "name = Bad weapon do not choose me"
//-----------------------------------------------------------------------------
// weaponId 7
MorphingWeaponSetId "Minelayer"
MorphingWeaponSetData "name = Minelayer"
MorphingWeaponSetData "aimMode = 1"
MorphingWeaponSetData "aimConePitchAngle = 0"
MorphingWeaponSetData "aimConeYawAngle = 0"
MorphingWeaponSetData "firingRate = .5"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 5"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 4"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_Mine_L3"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileSpeed = 5.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 128.0"
MorphingWeaponSetData "projectileMass = 20.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 0.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 3"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 128.0"
MorphingWeaponSetData "exploderMinDamage = 30"
MorphingWeaponSetData "exploderMaxDamage = 60"
MorphingWeaponSetData "exploderBlastForce = 700.0"
MorphingWeaponSetData "exploderMinBlastRadius = 6.8"
MorphingWeaponSetData "exploderMedBlastRadius = 4.0"
MorphingWeaponSetData "exploderFullBlastRadius = 2.0"
MorphingWeaponSetData "exploderDetonationDelay = 30.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = .5"
MorphingWeaponSetData "exploderRumbleLeftMotor = 1.0"
MorphingWeaponSetData "exploderRumbleRightMotor = 0.5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = .5"
MorphingWeaponSetData "fireRumbleDuration = .125"
MorphingWeaponSetData "fireRumbleLeftMotor = 1.0"
MorphingWeaponSetData "fireMessages = 18"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 7"
MorphingWeaponSetData "mountId = 2"
MorphingWeaponSetData "meshId = 7"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 0"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 8
MorphingWeaponSetId "Laser"
laserBeamVtileScale  0.02
laserBeamUspeed   0.00
laserBeamVspeed   4.00
laserBeamMaxWidth  0.09
laserBeamMinWidth  0.09
laserBeamInDuration  0.1240
laserBeamOutDuration 0.1240
MorphingWeaponSetData "name = Laser"
MorphingWeaponSetData "isLaser = true"
MorphingWeaponSetData "aimMode = 2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 55"
MorphingWeaponSetData "firingRate = 14.0"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = 0"
MorphingWeaponSetData "spreadAngleY = 0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 4"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 2"
MorphingWeaponSetData "fullReloadPenalty = 6"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = jh_Bullet"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 18"
MorphingWeaponSetData "projectileMinDamage = 18"
MorphingWeaponSetData "projectileSpeed = 20000.0"
MorphingWeaponSetData "projectileSpeedOffset = 10.0"
MorphingWeaponSetData "projectileRange = 96.0"
MorphingWeaponSetData "projectileMass = 0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 96.0"
MorphingWeaponSetData "exploderBlastForce = 0.0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "dryFireMessages = 26"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.125"
MorphingWeaponSetData "fireRumbleLeftMotor = 0.35"
MorphingWeaponSetData "fireMessages = 22"
MorphingWeaponSetData "offMessages = 56"
MorphingWeaponSetData "onMessages = 55"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 8"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 17"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 6"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
//weaponId 9
MorphingWeaponSetId "TwinRifle"
MorphingWeaponSetData "name = Twin Rifle"
MorphingWeaponSetData "aimMode = 0"
MorphingWeaponSetData "aimConePitchAngle = 40"
MorphingWeaponSetData "aimConeYawAngle = 45"
MorphingWeaponSetData "firingRate = 1.25"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 7"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 4"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_RifleBullet"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 60"
MorphingWeaponSetData "projectileMinDamage = 60"
MorphingWeaponSetData "projectileSpeed = 172.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 512.0"
MorphingWeaponSetData "projectileMass = 25.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 512.0"
MorphingWeaponSetData "exploderMinDamage = 45"
MorphingWeaponSetData "exploderMaxDamage = 70"
MorphingWeaponSetData "exploderBlastForce = 550.0"
MorphingWeaponSetData "exploderMinBlastRadius = 6.0"
MorphingWeaponSetData "exploderMedBlastRadius = 5.0"
MorphingWeaponSetData "exploderFullBlastRadius = 4.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 2.0"
MorphingWeaponSetData "exploderRumbleRightMotor = 2.0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 2.0"
MorphingWeaponSetData "fireMessages = 7"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "shellCasingMessage = 24"
MorphingWeaponSetData "shellCasingTriggerLogic = 1"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 9"
MorphingWeaponSetData "mountId = 1"
MorphingWeaponSetData "meshId = 14"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 2"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "reticuleKp = .10"
//-----------------------------------------------------------------------------
//weaponId 10
MorphingWeaponSetId "HeavyStubber"
MorphingWeaponSetData "name = 20mm Cannon"
MorphingWeaponSetData "aimMode = 0"
MorphingWeaponSetData "aimConePitchAngle = 40"
MorphingWeaponSetData "aimConeYawAngle = 45"
MorphingWeaponSetData "firingRate = 4.0"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = 0.1"
MorphingWeaponSetData "spreadAngleY = 0.1"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 8"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 4"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_StubberBullet"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 45"
MorphingWeaponSetData "projectileMinDamage = 45"
MorphingWeaponSetData "projectileSpeed = 196.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 512.0"
MorphingWeaponSetData "projectileMass = 1.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 512.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 2.0"
MorphingWeaponSetData "exploderRumbleRightMotor = 2.0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 2.0"
MorphingWeaponSetData "fireMessages = 6"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "shellCasingMessage = 23"
MorphingWeaponSetData "shellCasingTriggerLogic = 5"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 10"
MorphingWeaponSetData "mountId = 1"
MorphingWeaponSetData "meshId = 18"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 2"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "reticuleKp = .10"
//-----------------------------------------------------------------------------
// weaponId 11
MorphingWeaponSetId "RamPlate"
MorphingWeaponSetData "name = Ram"
MorphingWeaponSetData "meshId = 5"
ramPlateOffensiveScalar 1.5
ramPlateDefenseScalar .3
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "mountId = 5"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 11"
//-----------------------------------------------------------------------------
// weaponId 12
MorphingWeaponSetId "MiniRockets"
MorphingWeaponSetData "name = Mini-Rockets"
MorphingWeaponSetData "aimMode=2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 55"
MorphingWeaponSetData "firingRate = 1.25"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 3.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = .066"
MorphingWeaponSetData "maxFireTime = 5"
MorphingWeaponSetData "reloadDelay = 1"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 3"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_Rocket"
MorphingWeaponSetData "projectileCount = 4"
MorphingWeaponSetData "projectileSpeed = 75.0"
MorphingWeaponSetData "projectileSpeedOffset = 5.0"
MorphingWeaponSetData "projectileRange = 64.0"
MorphingWeaponSetData "projectileMass = 5.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 64.0"
MorphingWeaponSetData "exploderMinDamage = 20"
MorphingWeaponSetData "exploderMaxDamage = 30"
MorphingWeaponSetData "exploderBlastForce = 100.0"
MorphingWeaponSetData "exploderMinBlastRadius = 5.0"
MorphingWeaponSetData "exploderMedBlastRadius = 4.0"
MorphingWeaponSetData "exploderFullBlastRadius = 3.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 0.5"
MorphingWeaponSetData "exploderRumbleRightMotor = 0.5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = .5"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 0.75"
MorphingWeaponSetData "fireMessages = 0"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 52"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.25"
MorphingWeaponSetData "shellCasingMessage = 0"
MorphingWeaponSetData "shellCasingTriggerLogic = 0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 12"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 16"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 4"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 13
MorphingWeaponSetId "ReverseGrenadier"
MorphingWeaponSetData "name = Rear Grenades"
MorphingWeaponSetData "aimMode = 0"
MorphingWeaponSetData "aimConePitchAngle = 0"
MorphingWeaponSetData "aimConeYawAngle = 0"
MorphingWeaponSetData "firingRate = .75"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 5"
MorphingWeaponSetData "spreadAngleY = 5"
MorphingWeaponSetData "volleySpacing = .10"
MorphingWeaponSetData "maxFireTime = 4"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 4"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = jh_Grenade"
MorphingWeaponSetData "projectileCount = 6"
MorphingWeaponSetData "projectileMaxDamage = 20"
MorphingWeaponSetData "projectileMinDamage = 10"
MorphingWeaponSetData "projectileSpeed = 30.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 48.0"
MorphingWeaponSetData "projectileMass = 2.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 48.0"
MorphingWeaponSetData "exploderMinDamage = 15"
MorphingWeaponSetData "exploderMaxDamage = 25"
MorphingWeaponSetData "exploderBlastForce = 200.0"
MorphingWeaponSetData "exploderMinBlastRadius = 4.0"
MorphingWeaponSetData "exploderMedBlastRadius = 3.0"
MorphingWeaponSetData "exploderFullBlastRadius = 2.0"
MorphingWeaponSetData "exploderDetonationDelay = 2.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = .5"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = .5"
MorphingWeaponSetData "exploderRumbleLeftMotor = .5"
MorphingWeaponSetData "exploderRumbleRightMotor = .5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 0.5"
MorphingWeaponSetData "fireRumbleDuration = 0.125"
MorphingWeaponSetData "fireRumbleLeftMotor = .5"
MorphingWeaponSetData "fireMessages = 30"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "smokeLifeTime = 4.0"
MorphingWeaponSetData "smokeStunTime = 4.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 5"
MorphingWeaponSetData "mountId = 2"
MorphingWeaponSetData "meshId = 2"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 0"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 14
MorphingWeaponSetId "Missiles"
MorphingWeaponSetData "name = Titan Missiles"
MorphingWeaponSetData "aimMode=2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 55"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = False"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 4"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 5"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_Missile"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileSpeed = 95.0"
MorphingWeaponSetData "projectileSpeedOffset = 5.0"
MorphingWeaponSetData "projectileRange = 128.0"
MorphingWeaponSetData "projectileMass = 10.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 0.4"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 128.0"
MorphingWeaponSetData "exploderMinDamage = 100"
MorphingWeaponSetData "exploderMaxDamage = 150"
MorphingWeaponSetData "exploderBlastForce = 300.0"
MorphingWeaponSetData "exploderMinBlastRadius = 7.0"
MorphingWeaponSetData "exploderMedBlastRadius = 6.0"
MorphingWeaponSetData "exploderFullBlastRadius =5.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 1.5"
MorphingWeaponSetData "exploderRumbleRightMotor = 0.5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 0.4"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 1.0"
MorphingWeaponSetData "fireMessages = 14"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 3"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 20"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 3"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "reticuleKp = .10"
//-----------------------------------------------------------------------------
// weaponId 15
MorphingWeaponSetId "HomingMissiles"
MorphingWeaponSetData "name = Homing Missiles"
MorphingWeaponSetData "aimMode=2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 55"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 5"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 5"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_homingmissile"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileSpeed = 100.0"
MorphingWeaponSetData "projectileSpeedOffset = 5.0"
MorphingWeaponSetData "projectileRange = 128.0"
MorphingWeaponSetData "projectileMass = 10.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 0.4"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 128.0"
MorphingWeaponSetData "exploderMinDamage = 75"
MorphingWeaponSetData "exploderMaxDamage = 135"
MorphingWeaponSetData "exploderBlastForce = 300.0"
MorphingWeaponSetData "exploderMinBlastRadius = 5.0"
MorphingWeaponSetData "exploderMedBlastRadius = 4.0"
MorphingWeaponSetData "exploderFullBlastRadius =3.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 1.5"
MorphingWeaponSetData "exploderRumbleRightMotor = 0.5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 0.4"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 1.0"
MorphingWeaponSetData "fireMessages = 15"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 3"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 6"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 3"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "reticuleKp = .10"
//-----------------------------------------------------------------------------
// weaponId 16
MorphingWeaponSetId "Rockets"
MorphingWeaponSetData "name = Hellfire Rockets"
MorphingWeaponSetData "aimMode=2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 55"
MorphingWeaponSetData "firingRate = 1"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = 0.8"
MorphingWeaponSetData "spreadAngleY = 0.3"
MorphingWeaponSetData "volleySpacing = .066"
MorphingWeaponSetData "maxFireTime = 3"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 1"
MorphingWeaponSetData "fullReloadPenalty = 5"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_Rocket_L3"
MorphingWeaponSetData "projectileCount = 5"
MorphingWeaponSetData "projectileSpeed = 75.0"
MorphingWeaponSetData "projectileSpeedOffset = 5.0"
MorphingWeaponSetData "projectileRange = 64.0"
MorphingWeaponSetData "projectileMass = 5.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 64.0"
MorphingWeaponSetData "exploderMinDamage = 20"
MorphingWeaponSetData "exploderMaxDamage = 34"
MorphingWeaponSetData "exploderBlastForce = 100.0"
MorphingWeaponSetData "exploderMinBlastRadius = 4.0"
MorphingWeaponSetData "exploderMedBlastRadius = 3.0"
MorphingWeaponSetData "exploderFullBlastRadius = 2.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "exploderMinDamage = 10"
MorphingWeaponSetData "exploderRumbleLeftMotor = 0.5"
MorphingWeaponSetData "exploderRumbleRightMotor = 0.5"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = .5"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 0.75"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 51"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.25"
MorphingWeaponSetData "shellCasingMessage = 0"
MorphingWeaponSetData "shellCasingTriggerLogic = 0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 12"
MorphingWeaponSetData "mountId = 3"
MorphingWeaponSetData "meshId = 19"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 4"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
//-----------------------------------------------------------------------------
// weaponId 17
MorphingWeaponSetId "Flamethrower"
MorphingWeaponSetData "name = Flamethrower"
MorphingWeaponSetData "aimMode = 0"
MorphingWeaponSetData "aimConePitchAngle = 0"
MorphingWeaponSetData "aimConeYawAngle = 0"
MorphingWeaponSetData "firingRate = 5"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = 4.0"
MorphingWeaponSetData "spreadAngleY = 4.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 6"
MorphingWeaponSetData "reloadDelay = 1.5"
MorphingWeaponSetData "reloadTime = 2"
MorphingWeaponSetData "fullReloadPenalty = 6"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = bg_flamer"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 18"
MorphingWeaponSetData "projectileMinDamage = 18"
MorphingWeaponSetData "projectileSpeed = 85.0"
MorphingWeaponSetData "projectileSpeedOffset = 4.0"
MorphingWeaponSetData "projectileRange = 40.0"
MorphingWeaponSetData "projectileMass = 0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "effectiveMinRange = 0"
MorphingWeaponSetData "effectiveMaxRange = 40"
MorphingWeaponSetData "exploderBlastForce = 0.0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.125"
MorphingWeaponSetData "fireRumbleLeftMotor = 0.35"
MorphingWeaponSetData "fireMessages = 0"
MorphingWeaponSetData "offMessages = 58"
MorphingWeaponSetData "onMessages = 57"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "smokeLifeTime = 4.0"
MorphingWeaponSetData "smokeStunTime = 4.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 6"
MorphingWeaponSetData "mountId = 2"
MorphingWeaponSetData "meshId = 13"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 6"
MorphingWeaponSetData "reticuleKd = .05"
MorphingWeaponSetData "reticuleKp = .05"
MorphingWeaponSetData "flameStickyDamage = 30"
//-----------------------------------------------------------------------------
// weaponId 18
MorphingWeaponSetId "Cannon"
MorphingWeaponSetData "name = Tank Gun"
MorphingWeaponSetData "aimMode = 2"
MorphingWeaponSetData "aimConePitchAngle = 45"
MorphingWeaponSetData "aimConeYawAngle = 55"
MorphingWeaponSetData "firingRate = .5"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "maxFireTime = 3"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "reloadTime = 2.0"
MorphingWeaponSetData "fullReloadPenalty = 4.0"
MorphingWeaponSetData "recoilMass = 100"
MorphingWeaponSetData "projectilePid = fa_CannonBulletLarge"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileMaxDamage = 50"
MorphingWeaponSetData "projectileMinDamage = 50"
MorphingWeaponSetData "projectileSpeed = 196.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileRange = 512.0"
MorphingWeaponSetData "projectileMass = 10.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "projectileIgnoreArmor = 1"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 10"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 512.0"
MorphingWeaponSetData "exploderMinDamage = 0"
MorphingWeaponSetData "exploderMaxDamage = 0"
MorphingWeaponSetData "exploderBlastForce = 0"
MorphingWeaponSetData "exploderMinBlastRadius = 0"
MorphingWeaponSetData "exploderMedBlastRadius = 0"
MorphingWeaponSetData "exploderFullBlastRadius = 0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 1"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 2.0"
MorphingWeaponSetData "exploderRumbleRightMotor = 2.0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "fireRumbleLeftMotor = 2.0"
MorphingWeaponSetData "fireMessages = 8"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "shellCasingMessage = 24"
MorphingWeaponSetData "shellCasingTriggerLogic = 1"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "iconId = 13"
MorphingWeaponSetData "mountId = 1"
MorphingWeaponSetData "meshId = 9"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "reticule = 2"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "reticuleKp = .10"
//-----------------------------------------------------------------------------
// weaponId 19
MorphingWeaponSetId "Mortar"
MorphingWeaponCopyData "Missiles"
MorphingWeaponSetData "name = Earthshaker"
MorphingWeaponSetData "discardWhenEmpty = true"
MorphingWeaponSetData "firingRate = .5"
MorphingWeaponSetData "maxFireTime = 2"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "projectilePid = fa_mortarshell"
MorphingWeaponSetData "projectileSpeed = 60.0"
MorphingWeaponSetData "aimMode=0"
MorphingWeaponSetData "exploderMinDamage = 150"
MorphingWeaponSetData "exploderMaxDamage = 500"
MorphingWeaponSetData "exploderFullBlastRadius =10.0"
MorphingWeaponSetData "exploderMedBlastRadius = 15.0"
MorphingWeaponSetData "exploderMinBlastRadius = 20.0"
MorphingWeaponSetData "exploderBlastForce = 1500.0"
MorphingWeaponSetData "exploderDetonationDelay = 1.0"
MorphingWeaponSetData "meshId = 4"
MorphingWeaponSetData "mountId = 4"
MorphingWeaponSetData "fireMessages = 39"
MorphingWeaponSetData "reloadDelay = 1000000.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "targetVisDistance = 35.0"
// audio: XACT weap:missile2
MorphingWeaponSetData "iconId = 0"
//-----------------------------------------------------------------------------
// weaponId 20
MorphingWeaponSetId "FireBomb"
MorphingWeaponCopyData "Missiles"
MorphingWeaponSetData "name = Napalm"
MorphingWeaponSetData "discardWhenEmpty = true"
MorphingWeaponSetData "firingRate = .33"
MorphingWeaponSetData "maxFireTime = 9"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "projectilePid = bg_NapalmDrum"
MorphingWeaponSetData "projectileSpeed = 60.0"
MorphingWeaponSetData "aimMode=0"
MorphingWeaponSetData "exploderMinDamage = 150"
MorphingWeaponSetData "exploderMaxDamage = 250"
MorphingWeaponSetData "exploderFullBlastRadius =10.0"
MorphingWeaponSetData "exploderMedBlastRadius = 15.0"
MorphingWeaponSetData "exploderMinBlastRadius = 20.0"
MorphingWeaponSetData "flameStickyDamage = 50"
MorphingWeaponSetData "exploderBlastForce = 1.0"
MorphingWeaponSetData "meshId = 4"
MorphingWeaponSetData "mountId = 4"
MorphingWeaponSetData "fireMessages = 27"
MorphingWeaponSetData "reloadDelay = 1000000.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "targetVisDistance = 35.0"
// audio: XACT weap:missile2
MorphingWeaponSetData "iconId = 0"
//-----------------------------------------------------------------------------
// weaponId 21
MorphingWeaponSetId "NailBomb"
MorphingWeaponCopyData "Missiles"
MorphingWeaponSetData "name = Nail Bomb"
MorphingWeaponSetData "discardWhenEmpty = true"
MorphingWeaponSetData "firingRate = .5"
MorphingWeaponSetData "maxFireTime = 6"
MorphingWeaponSetData "continuousFire = false"
MorphingWeaponSetData "projectilePid = bg_nailbombshell"
MorphingWeaponSetData "projectileIgnoreArmor = 1"
MorphingWeaponSetData "exploderIgnoreArmor = 1"
MorphingWeaponSetData "projectileSpeed = 50.0"
MorphingWeaponSetData "aimMode=0"
MorphingWeaponSetData "exploderMinDamage = 50"
MorphingWeaponSetData "exploderMaxDamage = 50"
MorphingWeaponSetData "exploderFullBlastRadius =16.0"
MorphingWeaponSetData "exploderMedBlastRadius = 16.0"
MorphingWeaponSetData "exploderMinBlastRadius = 16.0"
MorphingWeaponSetData "exploderBlastForce = 100.0"
MorphingWeaponSetData "meshId = 4"
MorphingWeaponSetData "mountId = 4"
MorphingWeaponSetData "fireMessages = 42"
MorphingWeaponSetData "reloadDelay = 1000000.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "targetVisDistance = 35.0"
// audio: XACT weap:missile2
MorphingWeaponSetData "iconId = 0"
//-----------------------------------------------------------------------------
// weaponId 22
MorphingWeaponSetId "TurretMissiles"
MorphingWeaponSetData "name = Sentinel Missiles"
MorphingWeaponSetData "firingRate = 2"
MorphingWeaponSetData "continuousFire = False"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "aimConeYawAngle = 362"
MorphingWeaponSetData "aimConePitchAngle = 90"
MorphingWeaponSetData "maxFireTime = 2"
MorphingWeaponSetData "reloadTime = 2"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "fullReloadPenalty = 5"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "recoilMass = 0"
MorphingWeaponSetData "projectilePid = fa_Missile"
MorphingWeaponSetData "projectileSpeed = 75.0"
MorphingWeaponSetData "projectileSpeedOffset = 5.0"
MorphingWeaponSetData "projectileMass = 10.0"
MorphingWeaponSetData "exploderFullBlastRadius =5.0"
MorphingWeaponSetData "exploderMedBlastRadius = 6.0"
MorphingWeaponSetData "exploderMinBlastRadius = 7.0"
MorphingWeaponSetData "exploderBlastForce = 300.0"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileRange = 128.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 0.4"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 128.0"
MorphingWeaponSetData "exploderRumbleLeftMotor = 1.5"
MorphingWeaponSetData "exploderRumbleRightMotor = 0.5"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "fireRumbleLeftMotor = 1.0"
MorphingWeaponSetData "fireRightMotor = 0.4"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "reticule = 3"
MorphingWeaponSetData "meshId = 20"
MorphingWeaponSetData "alternateMeshId = -1"
MorphingWeaponSetData "mountId = 1"
MorphingWeaponSetData "reticuleKp = .10"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "iconId = 3"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "projectileIgnoreArmor = 0"
MorphingWeaponSetData "exploderIgnoreArmor = 0"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "exploderMinDamage = 50"
MorphingWeaponSetData "exploderMaxDamage = 100"
MorphingWeaponSetData "aimMode=2"
MorphingWeaponSetData "fireMessages = 14"
//-----------------------------------------------------------------------------
// weaponId 23
MorphingWeaponSetId "AutoCannon"
MorphingWeaponSetData "name = AutoCannon"
MorphingWeaponSetData "firingRate = 5"
MorphingWeaponSetData "continuousFire = true"
MorphingWeaponSetData "spreadAngleX = 0.0"
MorphingWeaponSetData "spreadAngleY = 0.0"
MorphingWeaponSetData "aimConeYawAngle = 15"
MorphingWeaponSetData "aimConePitchAngle = 15"
MorphingWeaponSetData "maxFireTime = 3"
MorphingWeaponSetData "reloadTime = 5.0"
MorphingWeaponSetData "fullReloadPenalty = 4.0"
MorphingWeaponSetData "reloadDelay = 2"
MorphingWeaponSetData "volleySpacing = 0"
MorphingWeaponSetData "recoilMass = 100"
MorphingWeaponSetData "projectileSpeed = 196.0"
MorphingWeaponSetData "projectileSpeedOffset = 0.0"
MorphingWeaponSetData "projectileMinDamage = 25"
MorphingWeaponSetData "projectileMaxDamage = 25"
MorphingWeaponSetData "projectileCount = 1"
MorphingWeaponSetData "projectileRange = 512.0"
MorphingWeaponSetData "projectileVelocityInheritScale = 1.0"
MorphingWeaponSetData "exploderDetonationDelay = 15.0"
MorphingWeaponSetData "exploderDetonationDelayOffset = 0"
MorphingWeaponSetData "effectiveMinRange = 0.0"
MorphingWeaponSetData "effectiveMaxRange = 512.0"
MorphingWeaponSetData "rumbleLeftMotor = 0.15"
MorphingWeaponSetData "rumbleRightMotor = 1.0"
MorphingWeaponSetData "rumbleDuration = 0.20"
MorphingWeaponSetData "exploderRumbleLeftMotor = 2.0"
MorphingWeaponSetData "exploderRumbleRightMotor = 2.0"
MorphingWeaponSetData "exploderRumbleDuration = 1.0"
MorphingWeaponSetData "fireRumbleLeftMotor = 2.0"
MorphingWeaponSetData "fireRightMotor = 1.0"
MorphingWeaponSetData "fireRumbleDuration = 0.25"
MorphingWeaponSetData "onMessages = 0"
MorphingWeaponSetData "offMessages = 0"
MorphingWeaponSetData "reloadStartMessages = 0"
MorphingWeaponSetData "reloadEndMessages = 0"
MorphingWeaponSetData "fullReloadStartMessages = 0"
MorphingWeaponSetData "fullReloadEndMessages = 0"
MorphingWeaponSetData "dryFireMessages = 31"
MorphingWeaponSetData "meshId = 18"
MorphingWeaponSetData "alternateMeshId = 18"
MorphingWeaponSetData "mountId = 0"
MorphingWeaponSetData "reticuleKp = .10"
MorphingWeaponSetData "reticuleKd = .10"
MorphingWeaponSetData "iconId = 13"
MorphingWeaponSetData "fireType = 0"
MorphingWeaponSetData "passThroughCount = 0"
MorphingWeaponSetData "projectileIgnoreArmor = 1"
MorphingWeaponSetData "exploderIgnoreArmor = 1"
MorphingWeaponSetData "ECM = 0"
MorphingWeaponSetData "smokeStunTime = 0.0"
MorphingWeaponSetData "smokeLifeTime = 0.0"
MorphingWeaponSetData "reticule = 2"
MorphingWeaponSetData "aimMode = 2"
MorphingWeaponSetData "projectilePid = fa_CannonBulletLarge"
MorphingWeaponSetData "exploderMinDamage = 0"
MorphingWeaponSetData "exploderMaxDamage = 0"
MorphingWeaponSetData "exploderFullBlastRadius = 0"
MorphingWeaponSetData "exploderMedBlastRadius = 0"
MorphingWeaponSetData "exploderMinBlastRadius = 0"
MorphingWeaponSetData "exploderBlastForce = 0"
MorphingWeaponSetData "projectileMass = 20.0"
MorphingWeaponSetData "fireMessages = 8"
MorphingWeaponSetData "shellCasingMessage = 24"
MorphingWeaponSetData "shellCasingTriggerLogic = 1"
MorphingWeaponSetData "passThroughCount = 10"
MorphingWeaponSetData "projectileMinDamage = 30"
MorphingWeaponSetData "projectileMaxDamage = 30"
//-----------------------------------------------------------------------------
