//
//  pita.psc - common initialization file for runtime
//


// debug menu options
DebugCommand "ProfileToggleDisplayMode"
DebugCommand "TweakData 1"
DebugCommand "ToggleAIs"
DebugCommand "dxDisplayMemStats -1"
DebugCommand "ToggleAi 0"
DebugCommand "ToggleAi 1"
DebugCommand "SplitScreenTest 2"
DebugCommand "SplitScreenTest 4"
DebugCommand "DrawPathMap"
DebugCommand "toggleWatchVerbosity -1"
DebugCommand "ShowPackCounts -1"
DebugCommand "printActiveObjectStats"
DebugCommand "PlantCamera"
DebugCommand "TeleportToCamera 0"
DebugCommand "TeleportToTarget 0"
DebugCommand "DebugPortals"
DebugCommand "gfxVertexDensityDebug 1"
DebugCommand "drawCheesyMirror -1"
DebugCommand "run preset2"
DebugCommand "ToggleDebugCam 1"

// Tweak
///DEBUG/// bind joy0_l3+joy0_dpadup pitaDebug 1
///DEBUG/// bind joy0_l3+joy0_dpaddown pitaDebug 0
///DEBUG/// bind joy0_r3+joy0_l3+joy0_l1 TweakData 1
///DEBUG/// bind joy1_r3+joy1_l3+joy1_l1 TweakData 1
///DEBUG/// bind joy0_square+joy0_dpadleft gfxDisplayAlpha -1
///DEBUG/// bind joy0_square+joy0_dpadright DoSingleStep
///DEBUG/// bind joy0_square+joy0_dpaddown printActiveObjectStats
///DEBUG/// bind joy0_dpadright+joy0_l3 GotoDebugPoint +1
///DEBUG/// bind joy0_dpadleft+joy0_l3  GotoDebugPoint -1
///DEBUG/// bind joy0_dpaddown+joy0_l3  GotoDebugPointNearest    0   // l3+dpaddown
///DEBUG/// bind joy0_dpadup+joy0_l3    GotoDebugPointNearestCam 0   // l3+dpadup
///DEBUG/// bind joy0_x+joy0_r3 ToggleDebugCam 1
///DEBUG/// bind joy0_square+joy0_r3 TeleportToTarget 0   // r3+black
///DEBUG/// bind joy0_square+joy0_dpadup nukeme 0
///DEBUG/// bind joy0_x+joy0_dpaddown toggleai 0
///DEBUG/// bind joy0_square+joy0_circle+joy0_back RebootToSystem

gbind f1 ToggleVertexDensityDebug 0
bind f2 ToggleVertexDensityDebugFreeze 0

bind f5 screenshot

run game.psc            // generated by makebuild
run DebugLevel.psc      // generated by makebuild
run pitaLocal.psc       // your own custom settings
run CareerScript.psc    // must be after local settings (or else makebuild breaks)

// must be after pitalocal
run dev.psc

