// generated by NetMakebuild 
perforceAutoUpdate 0 
perforcesync 
disableCacheSync 0 
auto~sim_config.Theme=AllThemes 
ModFileNameVerbose 0 
gfxDisableEverything 1 
ignoreCustomCreateErrors 2 
lazyHullUpdate 0 
lazyChunkUpdate 0 
lazyTextureUpdate 0 
lazyPackUpdate 0 
AutoUpdateBatchRefs 0 
targetPlatform 5 
enableSurfaceBreakup 1 
vertexPaintCache 1 
makeStreamTextures 1 
saveVertsWithMesh 0 
ServerPort 13337 
ServerIP "192.168.1.81" 
NetSlaveMode 
abort 
